apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runtime-argocd-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - runtime: pipeline1-runtime-argocd
        clusterURL: https://47.85.138.53:32050
  template:
    metadata:
      name: '{{runtime}}'
      namespace: argocd
    spec:
      project: demo-vcluster
      source:
        repoURL: https://github.com/Butterfly256-ai/demo-pipeline-argoevents-tekton.git
        targetRevision: main
        path: argocd/overlays/production
      destination:
        server: '{{clusterURL}}'
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
