apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cert-manager-secretstore
  namespace: cert-manager
spec:
  provider:
    vault:
      server: "http://47.85.138.53:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: cert-manager
data:
  token: aHZzLkFqblZWNjNsQWVuSnU4QjU4T3I4UENBWA==
